# Generated by Django 4.2.2 on 2023-06-07 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('elevator_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Under_Maintenance', 'Under_Maintenance')], max_length=30)),
                ('current_floor', models.IntegerField()),
                ('direction', models.CharField(choices=[('Upward', 'Upward'), ('Downward', 'Downward')], max_length=30)),
                ('doors_open', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ElevatorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator_app.elevator')),
            ],
        ),
    ]
